name: nekodroid
description: Unofficial android client for neko-sama.fr.
version: 1.0.0+1
homepage: https://github.com/zkayia/nekodroid
issue_tracker: https://github.com/zkayia/nekodroid/issues
repository: https://github.com/zkayia/nekodroid


publish_to: none


environment:
  sdk: ">=3.0.0"


dependencies:
  android_intent_plus: ^3.1.1
  audio_video_progress_bar: ^0.10.0
  boxicons:
    git:
      url: https://github.com/zkayia/dartpacks
      path: boxicons
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  lazy_load_scrollview: ^1.3.0
  nekosama:
    git:
      url: https://github.com/holy-crusader-py/nekosama_dart
      path: packages/nekosama
  nekosama_hive:
    git:
      url: https://github.com/holy-crusader-py/nekosama_dart
      path: packages/nekosama_hive
  package_info_plus: ^4.1.0
  path_provider: ^2.1.0
  share_plus: ^4.0.4
  version: ^2.0.0
  video_player: ^2.4.5

dev_dependencies:
  build_runner:
  dart_code_metrics: ^5.7.6
  device_preview: ^1.1.0
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/nekodroid_logo_app.png"
  adaptive_icon_background: "#262626"
  adaptive_icon_foreground: "assets/images/nekodroid_logo_app.png"

flutter_native_splash:
  color: "#fafafa"
  image: assets/images/nekodroid_logo_black.png
  color_dark: "#171717"
  image_dark: assets/images/nekodroid_logo_regular.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/player/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
