name: nekodroid
description: Unofficial android client for neko-sama.fr.
version: 1.0.0+1
homepage: https://github.com/zkayia/nekodroid
issue_tracker: https://github.com/zkayia/nekodroid/issues
repository: https://github.com/zkayia/nekodroid


publish_to: none


environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  nekosama_dart:
    git: https://github.com/zkayia/nekosama_dart
  android_intent_plus: ^3.1.1
  audio_video_progress_bar: ^0.10.0
  boxicons: ^2.1.3
  cached_network_image: ^3.2.0
  easy_localization: ^3.0.0
  flutter_inappwebview: ^5.4.1+1
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  hive_flutter: ^1.1.0
  lazy_load_scrollview: ^1.3.0
  package_info_plus: ^1.4.2
  share_plus: ^4.0.4
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  device_preview: ^1.1.0
  dart_code_metrics: ^4.15.2

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/nekodroid_logo_app.png"
  adaptive_icon_background: "#262626"
  adaptive_icon_foreground: "assets/images/nekodroid_logo_app.png"

flutter_native_splash:
  color: "#fafafa"
  image: assets/images/nekodroid_logo_black.png
  color_dark: "#171717"
  image_dark: assets/images/nekodroid_logo_regular.png

flutter:
  uses-material-design: false
  assets:
    - assets/player/
    - assets/translations/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700